<a href="https://colab.research.google.com/github/julian-masdatascience/ML/blob/master/A_Z/01_Gestion_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Conexión con datos desde Colab

## Opción 1 : Descargar los datos en VM de Google Colab

In [0]:
import urllib.request # para descargar de URL
url = 'https://github.com/julian-masdatascience/ML/raw/master/A_Z/DS/Data.csv' 
urllib.request.urlretrieve(url,"Data.csv")

('Data.csv', <http.client.HTTPMessage at 0x7f58cbd0ac18>)

In [0]:
%ls ## miro lo que existe en la VM

Data.csv  sample_data/


In [0]:
dataset = pd.read_csv("Data.csv")

## Opción 2 : Descargar directamente desde una URL

In [0]:
# Missing_data.py
import pandas as pd
url = 'https://github.com/julian-masdatascience/ML/raw/master/A_Z/DS/Data.csv'
dataset = pd.read_csv(url)

## Opción 3: Usar Gdrive

In [0]:
from google.colab import drive
drive.mount('/content/drive')

# 2. Gestionar datos 
## 2.1 Datos Nulos

In [6]:
!pip install --upgrade sklearn

Requirement already up-to-date: sklearn in /usr/local/lib/python3.6/dist-packages (0.0)


In [0]:

# Liberias que se van a usar 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# X variables indepoendeintes , Y valor a predecir 
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values



In [61]:
## antes
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [62]:
## despues
# Revisar los valores núlos 
from sklearn.impute  import SimpleImputer  ## https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## 2.2 Datos Categoricos

In [63]:
#Colab no tiene ninguna variable
print (X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [0]:
# Data Preprocessing

# Codificar datos categoricos
# Codificar variables idependientes 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

In [65]:
print(X)
## Se han codificado los valores, y ahora? que problema se puede presentar? 

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [67]:
# Voy a utilizar la variable X1 para que se identifica la transformación 
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Paises", OneHotEncoder(), [0])], remainder = 'passthrough')
X1 = ct.fit_transform(X)
print(X1)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [70]:
# Para trabajar con los datos es necesario convertirlos en un arreglo y se realiza con la siguiente función 
X = np.array(ct.fit_transform(X), dtype=np.float)
print(X)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 2.70000000e+01
  4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 3.00000000e+01
  5.40000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+01
  5.80000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 5.00000000e+01
  8.30000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.70000000e+01
  6.70000000e+04]]


In [71]:
# ahora con los datos objetivos a predecir 
from sklearn.preprocessing import LabelEncoder
print(y)
y = LabelEncoder().fit_transform(y)
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
[0 1 0 0 1 1 0 1 0 1]


## 2.3 Estandarizar datos

Siempre que utilicemos los algoritmos en Machine Learning es necesario que tengamos una separación de los datasets en entrenamiento y pruebas, ¿por que? ya lo miraremos en clase. 

In [0]:
# Partimos el dataset en dos subgrupos uno de entrenamiento y otro de prueba, en este caso 20% de los datos se iran de pruebas
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


Estandarizar los datos nos permite entrengar de una mejor forma los algortimos , ¿ por que ?, ya lo vamos a mirar.

In [76]:
print(X_train)
print("-----")
print(y_train)

[[0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.70000000e+01
  6.70000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 2.70000000e+01
  4.80000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+01
  5.80000000e+04]]
-----
[1 1 1 0 1 0 0 1]


In [0]:
# Escalar caracteristicas
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train.reshape(-1,1))

In [78]:
print(X_train)
print("-----")
print(y_train)

[[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]
-----
[[ 0.77459667]
 [ 0.77459667]
 [ 0.77459667]
 [-1.29099445]
 [ 0.77459667]
 [-1.29099445]
 [-1.29099445]
 [ 0.77459667]]
