<a href="https://colab.research.google.com/github/julian-masdatascience/ML/blob/master/02_Regresion_01-Multinomial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regresión Lineal
## 1. Importar librerias

In [0]:
## Basicas
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
## Datos
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
## ML
from sklearn.linear_model import LinearRegression
np.set_printoptions(precision=1,suppress=True)

## 2. Importar Datos

In [10]:
url = 'https://github.com/julian-masdatascience/ML/raw/master/A_Z/DS/fondo_inversion.csv'
dataset = pd.read_csv(url)
dataset.head()

R&D  Administrativo  Marketing      Estado   Ganancia
0  165349.20       136897.80  471784.10    New York  192261.83
1  162597.70       151377.59  443898.53  California  191792.06
2  153441.51       101145.55  407934.54     Florida  191050.39
3  144372.41       118671.85  383199.62    New York  182901.99
4  142107.34        91391.77  366168.42     Florida  166187.94

In [12]:
dataset.describe()

R&D  Administrativo      Marketing       Ganancia
count      50.000000       50.000000      50.000000      50.000000
mean    73721.615600   121344.639600  211025.097800  112012.639200
std     45902.256482    28017.802755  122290.310726   40306.180338
min         0.000000    51283.140000       0.000000   14681.400000
25%     39936.370000   103730.875000  129300.132500   90138.902500
50%     73051.080000   122699.795000  212716.240000  107978.190000
75%    101602.800000   144842.180000  299469.085000  139765.977500
max    165349.200000   182645.560000  471784.100000  192261.830000

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   R&D             50 non-null     float64
 1   Administrativo  50 non-null     float64
 2   Marketing       50 non-null     float64
 3   Estado          50 non-null     object 
 4   Ganancia        50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [0]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

## 3. Trabajar con los datos

### 3.1 Normalizar datos

In [63]:
## Codifico el Estado
X[:,3]


array(['New York', 'California', 'Florida', 'New York', 'Florida',
       'New York', 'California', 'Florida', 'New York', 'California',
       'Florida', 'California', 'Florida', 'California', 'Florida',
       'New York', 'California', 'New York', 'Florida', 'New York',
       'California', 'New York', 'Florida', 'Florida', 'New York',
       'California', 'Florida', 'New York', 'Florida', 'New York',
       'Florida', 'New York', 'California', 'Florida', 'California',
       'New York', 'Florida', 'California', 'New York', 'California',
       'California', 'Florida', 'California', 'New York', 'California',
       'New York', 'Florida', 'California', 'New York', 'California'],
      dtype=object)

In [0]:
## from sklearn.preprocessing import OneHotEncoder
## from sklearn.compose import ColumnTransformer
## from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])
ct =ColumnTransformer([('encoder', OneHotEncoder(), [3])],
remainder='passthrough')
X= np.array(ct.fit_transform(X), dtype=np.float)

In [65]:
## Codifico el Estado
print(X[0:3])

[[     0.       0.       1.  165349.2 136897.8 471784.1]
 [     1.       0.       0.  162597.7 151377.6 443898.5]
 [     0.       1.       0.  153441.5 101145.6 407934.5]]


In [0]:
# Elmino el problema de la variable trampa Dummy 
X = X[:, 1:]

In [67]:
print(X[0:3])

[[     0.       1.  165349.2 136897.8 471784.1]
 [     0.       0.  162597.7 151377.6 443898.5]
 [     1.       0.  153441.5 101145.6 407934.5]]


In [68]:
len(X)

50

### 3.2 Separar entrenamiento y pruebas 

In [69]:
## from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.2, random_state = 0)
print("Registros en X_train "+str(len(X_train)))
print("Registros en X_test "+str(len(X_test)))

Registros en X_train 40
Registros en X_test 10


In [70]:
print(X_train)
print("------")
print(y_train)

[[     1.       0.   55493.9 103057.5 214634.8]
 [     0.       1.   46014.   85047.4 205517.6]
 [     1.       0.   75328.9 144136.  134050.1]
 [     0.       0.   46426.1 157693.9 210797.7]
 [     1.       0.   91749.2 114175.8 294919.6]
 [     1.       0.  130298.1 145530.1 323876.7]
 [     1.       0.  119943.2 156547.4 256512.9]
 [     0.       1.    1000.2 124153.    1903.9]
 [     0.       1.     542.   51743.2      0. ]
 [     0.       1.   65605.5 153032.1 107138.4]
 [     0.       1.  114523.6 122616.8 261776.2]
 [     1.       0.   61994.5 115641.3  91131.2]
 [     0.       0.   63408.9 129219.6  46085.2]
 [     0.       0.   78013.1 121597.6 264346.1]
 [     0.       0.   23640.9  96189.6 148001.1]
 [     0.       0.   76253.9 113867.3 298664.5]
 [     0.       1.   15505.7 127382.3  35534.2]
 [     0.       1.  120542.5 148719.  311613.3]
 [     0.       0.   91992.4 135495.1 252664.9]
 [     0.       0.   64664.7 139553.2 137962.6]
 [     0.       1.  131876.9  99814.7 36

## 4. Crear Modelo ML

In [0]:
# from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Predicting the Test set results
y_pred = regressor.predict(X_test)


In [72]:
#comparemos
print("y_test" + str(y_test))
print("y_pred" + str(y_pred))

y_test[103282.4 144259.4 146122.   77798.8 191050.4 105008.3  81229.1  97483.6
 110352.2 166187.9]
y_pred[103015.2 132582.3 132447.7  71976.1 178537.5 116161.2  67851.7  98791.7
 113969.4 167921.1]


In [73]:
print("y_test " + str(y_test))
print("y_pred " + str(y_pred))

y_test [103282.4 144259.4 146122.   77798.8 191050.4 105008.3  81229.1  97483.6
 110352.2 166187.9]
y_pred [103015.2 132582.3 132447.7  71976.1 178537.5 116161.2  67851.7  98791.7
 113969.4 167921.1]


## 5. Analizar resultados

In [74]:
regressor.score(X_test,y_test)

0.9347068473282986