<a href="https://colab.research.google.com/github/julian-masdatascience/ML/blob/master/02_Regresion_01-Multinomial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regresión Lineal
## 1. Importar librerias

In [0]:
## Basicas
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
## Datos
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
## ML
from sklearn.linear_model import LinearRegression
np.set_printoptions(precision=1,suppress=True)

## 2. Importar Datos

In [10]:
url = 'https://github.com/julian-masdatascience/ML/raw/master/A_Z/DS/fondo_inversion.csv'
dataset = pd.read_csv(url)
dataset.head()

R&D  Administrativo  Marketing      Estado   Ganancia
0  165349.20       136897.80  471784.10    New York  192261.83
1  162597.70       151377.59  443898.53  California  191792.06
2  153441.51       101145.55  407934.54     Florida  191050.39
3  144372.41       118671.85  383199.62    New York  182901.99
4  142107.34        91391.77  366168.42     Florida  166187.94

In [12]:
dataset.describe()

R&D  Administrativo      Marketing       Ganancia
count      50.000000       50.000000      50.000000      50.000000
mean    73721.615600   121344.639600  211025.097800  112012.639200
std     45902.256482    28017.802755  122290.310726   40306.180338
min         0.000000    51283.140000       0.000000   14681.400000
25%     39936.370000   103730.875000  129300.132500   90138.902500
50%     73051.080000   122699.795000  212716.240000  107978.190000
75%    101602.800000   144842.180000  299469.085000  139765.977500
max    165349.200000   182645.560000  471784.100000  192261.830000

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   R&D             50 non-null     float64
 1   Administrativo  50 non-null     float64
 2   Marketing       50 non-null     float64
 3   Estado          50 non-null     object 
 4   Ganancia        50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [0]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

## 3. Trabajar con los datos

### 3.1 Normalizar datos

In [114]:
## Codifico el Estado
X[:,3]


array(['New York', 'California', 'Florida', 'New York', 'Florida',
       'New York', 'California', 'Florida', 'New York', 'California',
       'Florida', 'California', 'Florida', 'California', 'Florida',
       'New York', 'California', 'New York', 'Florida', 'New York',
       'California', 'New York', 'Florida', 'Florida', 'New York',
       'California', 'Florida', 'New York', 'Florida', 'New York',
       'Florida', 'New York', 'California', 'Florida', 'California',
       'New York', 'Florida', 'California', 'New York', 'California',
       'California', 'Florida', 'California', 'New York', 'California',
       'New York', 'Florida', 'California', 'New York', 'California'],
      dtype=object)

In [0]:
## from sklearn.preprocessing import OneHotEncoder
## from sklearn.compose import ColumnTransformer
## from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])
ct =ColumnTransformer([('encoder', OneHotEncoder(), [3])],
remainder='passthrough')
X= np.array(ct.fit_transform(X), dtype=np.float)

In [116]:
## Codifico el Estado
print(X[0:3])

[[     0.       0.       1.  165349.2 136897.8 471784.1]
 [     1.       0.       0.  162597.7 151377.6 443898.5]
 [     0.       1.       0.  153441.5 101145.6 407934.5]]


In [0]:
# Elmino el problema de la variable trampa Dummy 
X = X[:, 1:]

In [118]:
print(X[0:3])

[[     0.       1.  165349.2 136897.8 471784.1]
 [     0.       0.  162597.7 151377.6 443898.5]
 [     1.       0.  153441.5 101145.6 407934.5]]


In [119]:
len(X)

50

### 3.2 Separar entrenamiento y pruebas 

In [120]:
## from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.2, random_state = 0)
print("Registros en X_train "+str(len(X_train)))
print("Registros en X_test "+str(len(X_test)))

Registros en X_train 40
Registros en X_test 10


In [121]:
print(X_train)
print("------")
print(y_train)

[[     1.       0.   55493.9 103057.5 214634.8]
 [     0.       1.   46014.   85047.4 205517.6]
 [     1.       0.   75328.9 144136.  134050.1]
 [     0.       0.   46426.1 157693.9 210797.7]
 [     1.       0.   91749.2 114175.8 294919.6]
 [     1.       0.  130298.1 145530.1 323876.7]
 [     1.       0.  119943.2 156547.4 256512.9]
 [     0.       1.    1000.2 124153.    1903.9]
 [     0.       1.     542.   51743.2      0. ]
 [     0.       1.   65605.5 153032.1 107138.4]
 [     0.       1.  114523.6 122616.8 261776.2]
 [     1.       0.   61994.5 115641.3  91131.2]
 [     0.       0.   63408.9 129219.6  46085.2]
 [     0.       0.   78013.1 121597.6 264346.1]
 [     0.       0.   23640.9  96189.6 148001.1]
 [     0.       0.   76253.9 113867.3 298664.5]
 [     0.       1.   15505.7 127382.3  35534.2]
 [     0.       1.  120542.5 148719.  311613.3]
 [     0.       0.   91992.4 135495.1 252664.9]
 [     0.       0.   64664.7 139553.2 137962.6]
 [     0.       1.  131876.9  99814.7 36

## 4. Crear Modelo ML

In [0]:
# from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Predicting the Test set results
y_pred = regressor.predict(X_test)


In [123]:
#comparemos
print("y_test" + str(y_test))
print("y_pred" + str(y_pred))

y_test[103282.4 144259.4 146122.   77798.8 191050.4 105008.3  81229.1  97483.6
 110352.2 166187.9]
y_pred[103015.2 132582.3 132447.7  71976.1 178537.5 116161.2  67851.7  98791.7
 113969.4 167921.1]


In [124]:
print("y_test " + str(y_test))
print("y_pred " + str(y_pred))

y_test [103282.4 144259.4 146122.   77798.8 191050.4 105008.3  81229.1  97483.6
 110352.2 166187.9]
y_pred [103015.2 132582.3 132447.7  71976.1 178537.5 116161.2  67851.7  98791.7
 113969.4 167921.1]


## 5. Analizar resultados

In [125]:
regressor.score(X_test,y_test)

0.9347068473282986

In [0]:
#backwar
import statsmodels.regression.linear_model as sm
#Volvemos a traer la caracteristica dummy que eliminamos
X1 = np.append(X,values=np.ones((50,1)).astype(int),axis=1)

In [127]:
X1[0:3]

array([[     0. ,      1. , 165349.2, 136897.8, 471784.1,      1. ],
       [     0. ,      0. , 162597.7, 151377.6, 443898.5,      1. ],
       [     1. ,      0. , 153441.5, 101145.6, 407934.5,      1. ]])

In [0]:
X2 = np.append(arr=np.ones((50,1)).astype(int),values=X,axis=1)

In [129]:
X2[0:3]

array([[     1. ,      0. ,      1. , 165349.2, 136897.8, 471784.1],
       [     1. ,      0. ,      0. , 162597.7, 151377.6, 443898.5],
       [     1. ,      1. ,      0. , 153441.5, 101145.6, 407934.5]])

In [130]:
X=X2.copy()
X[0:3]

array([[     1. ,      0. ,      1. , 165349.2, 136897.8, 471784.1],
       [     1. ,      0. ,      0. , 162597.7, 151377.6, 443898.5],
       [     1. ,      1. ,      0. , 153441.5, 101145.6, 407934.5]])

In [0]:
X_opt = X[:,[0,1,2,3,4,5]]
regresor_OLS = sm.OLS(endog=y,exog=X_opt).fit()

In [133]:
regresor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Tue, 14 Apr 2020   Prob (F-statistic):           1.34e-27
Time:                        03:05:17   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.000    3.62e+04     6.4e+04
x1           198.7888   3371.007      0.059      0.953   -6595.030    6992.607
x2           -41.8870   3256.039     -0.013      0.990   -6604.003    6520.229
x3             0.8060      0.046     17.369      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [134]:
X_opt = X[:,[0,1,3,4,5]]
regresor_OLS = sm.OLS(endog=y,exog=X_opt).fit()
regresor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Tue, 14 Apr 2020   Prob (F-statistic):           8.49e-29
Time:                        03:11:52   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.870      7.537      0.000    3.67e+04    6.35e+04
x1           220.1585   2900.536      0.076      0.940   -5621.821    6062.138
x2             0.8060      0.046     17.606      0.000       0.714       0.898
x3            -0.0270      0.052     -0.523      0.604      -0.131       0.077
x4             0.0270      0.017      1.592      0.118      -0.007       0.061
==============================================================================
Omnibus:                       14.758   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.172
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [135]:
X_opt = X[:,[0,3,4,5]]
regresor_OLS = sm.OLS(endog=y,exog=X_opt).fit()
regresor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Tue, 14 Apr 2020   Prob (F-statistic):           4.53e-30
Time:                        03:12:08   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [137]:
X_opt = X[:,[0,3,5]]
regresor_OLS = sm.OLS(endog=y,exog=X_opt).fit()
regresor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Tue, 14 Apr 2020   Prob (F-statistic):           2.16e-31
Time:                        03:17:13   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [138]:
X_opt = X[:,[0,3]]
regresor_OLS = sm.OLS(endog=y,exog=X_opt).fit()
regresor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Tue, 14 Apr 2020   Prob (F-statistic):           3.50e-32
Time:                        03:19:35   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

Esto nos dice que el mayor impacto es de una sola variable , la cual es R&D